version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/base:2022.09

jobs:
  test:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
      - run:
          name: Build Docker image
          command: docker build -t anaks/react-test -f ./client/Dockerfile.dev ./client
      - run:
          name: Run tests
          command: docker run -e CI=true anaks/react-test npm run test
  deploy:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
      - run:
          name: Build Docker image
          command: |
            docker build -t anaks/multi-client ./client
            docker build -t anaks/multi-nginx ./nginx
            docker build -t anaks/multi-server ./server
            docker build -t anaks/multi-worker ./worker
      - run:
          name: Push Docker images to Docker Hub
          command: |
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ID}" --password-stdin
            docker push anaks/multi-client
            docker push anaks/multi-nginx
            docker push anaks/multi-server
            docker push anaks/multi-worker
workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main